{% set name = "reboost" %}
{% set version = "0.8.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reboost-{{ version }}.tar.gz
  sha256: f4a91d2b111d6599c9a357435766b89f859fbcd9788349939d3e283cccba2fe2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - reboost-optical = reboost.optmap.cli:optical_cli
    - reboost = reboost.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm >=7
    - pip
  run:
    - legend-pygeom-hpges
    - python >={{ python_min }}
    - hdf5plugin
    - colorlog
    - numpy
    - scipy
    - numba >=0.60
    - legend-pydataobj >=1.15.1
    - legend-pygeom-optics >=0.12.0
    - legend-pygeom-tools >=0.0.11
    - hist
    - dbetto
    - particle
    - pandas
    - matplotlib-base
    - pygama
    - pyg4ometry

test:
  imports:
    - reboost
  commands:
    - pip check
    - reboost -h
    - reboost-optical -h
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: LEGEND Monte-Carlo simulation post-processing
  home: https://github.com/legend-exp/reboost
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://reboost.readthedocs.io
  dev_url: https://github.com/legend-exp/reboost

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
